apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/deepforu47/learning
      title: GitHub Repo
      icon: github
    - url: 
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-
  definition:
    $text: ./petstore.yaml
